# fly.toml app configuration file generated for campuscart on 2025-11-08T12:13:39+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'campuscart'
primary_region = 'bom'

[build]
  [build.args]
    VITE_API_BASE_URL = "/api/v1"
    VITE_RAZORPAY_KEY_ID = "rzp_test_p5tUrU9KDgnQ0P"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
